//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoredModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DrugStoreEntities : DbContext
    {
        public DrugStoreEntities()
            : base("name=DrugStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("DrugStoreEntities", "ReportRangeAgentSales")]
        public virtual IQueryable<ReportRangeAgentSales_Result> ReportRangeAgentSales(Nullable<int> smonth, Nullable<int> emonth, Nullable<int> syear, Nullable<int> eyear)
        {
            var smonthParameter = smonth.HasValue ?
                new ObjectParameter("smonth", smonth) :
                new ObjectParameter("smonth", typeof(int));
    
            var emonthParameter = emonth.HasValue ?
                new ObjectParameter("emonth", emonth) :
                new ObjectParameter("emonth", typeof(int));
    
            var syearParameter = syear.HasValue ?
                new ObjectParameter("syear", syear) :
                new ObjectParameter("syear", typeof(int));
    
            var eyearParameter = eyear.HasValue ?
                new ObjectParameter("eyear", eyear) :
                new ObjectParameter("eyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ReportRangeAgentSales_Result>("[DrugStoreEntities].[ReportRangeAgentSales](@smonth, @emonth, @syear, @eyear)", smonthParameter, emonthParameter, syearParameter, eyearParameter);
        }
    }
}
